-file("/usr/lib/erlang/lib/parsetools-2.0.12/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(config_scanner).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/config/config_scanner.xrl", 35).

% Remove first and last
strip(TokenChars,TokenLen) -> 
    lists:sublist(TokenChars, 2, TokenLen - 2).

% Remove first and 2 last
strip2(TokenChars,TokenLen) -> 
    lists:sublist(TokenChars, 2, TokenLen - 3).

-file("/usr/lib/erlang/lib/parsetools-2.0.12/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/config_scanner.erl", 284).
yystate() -> 56.

yystate(63, [101|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 4, Tlen);
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,63};
yystate(62, [47|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [42|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [35|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [33|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [34|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,62};
yystate(61, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [47|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [35|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(60, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(60, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,60};
yystate(59, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(58, [47|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [42|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [35|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [33|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [34|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,58};
yystate(57, [114|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,57};
yystate(56, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line+1, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 101 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 111, C =< 115 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [98|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [97|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,55};
yystate(54, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(54, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line+1, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(50, [47|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [42|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [35|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [33|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [34|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,50};
yystate(49, [97|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,49};
yystate(48, [114|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,48};
yystate(47, [109|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 4, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,47};
yystate(46, [46|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 6, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,46};
yystate(45, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(43, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [108|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,41};
yystate(40, [117|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,40};
yystate(39, [117|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,39};
yystate(38, [47|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [35|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [33|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [34|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,38};
yystate(37, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(36, [47|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [35|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [33|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [34|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 46 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,36};
yystate(35, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 50, C =< 57 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, 5, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,34};
yystate(33, [115|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,33};
yystate(32, [101|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,32};
yystate(31, [110|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,31};
yystate(30, [47|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [35|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [33|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [34|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 46 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,30};
yystate(29, [48|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(6, Ics, Line, Tlen+1, 9, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,29};
yystate(28, [47|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [42|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [35|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [33|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [34|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,28};
yystate(27, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 50, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [101|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,25};
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,24};
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 4, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,23};
yystate(22, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 43 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, [47|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [42|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [35|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [33|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [34|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,20};
yystate(19, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,19};
yystate(18, [69|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 5, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(18, Ics, Line, Tlen+1, 5, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,18};
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,17};
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,16};
yystate(15, [97|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,15};
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, [47|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [42|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [35|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [33|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [34|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(13, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(13, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,13};
yystate(12, [47|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [42|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [35|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [33|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [34|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,12};
yystate(11, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(10, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 3, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(9, Ics, Line, Tlen+1, 3, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(9, Ics, Line, Tlen+1, 3, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 3, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,9};
yystate(8, [111|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,8};
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,7};
yystate(6, [46|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 6, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(6, Ics, Line, Tlen+1, 6, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,6};
yystate(5, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(3, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(3, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(1, [47|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [42|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [35|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [33|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [34|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [10|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 41 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,1};
yystate(0, [116|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLen, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, _, _, _) ->
    yyaction_7();
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLen, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLen, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLen, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/config/config_scanner.xrl", 14).
yyaction_0(TokenLine) ->
     { token, { boolean, TokenLine, true } } .

-compile({inline,yyaction_1/1}).
-file("src/config/config_scanner.xrl", 15).
yyaction_1(TokenLine) ->
     { token, { boolean, TokenLine, false } } .

-compile({inline,yyaction_2/3}).
-file("src/config/config_scanner.xrl", 16).
yyaction_2(TokenChars, TokenLen, TokenLine) ->
     S = strip (TokenChars, TokenLen),
     { token, { string, TokenLine, S } } .

-compile({inline,yyaction_3/2}).
-file("src/config/config_scanner.xrl", 18).
yyaction_3(TokenChars, TokenLine) ->
     { token, { uppercase_identifier, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_4/2}).
-file("src/config/config_scanner.xrl", 19).
yyaction_4(TokenChars, TokenLine) ->
     { token, { mix_identifier, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("src/config/config_scanner.xrl", 21).
yyaction_5(TokenChars, TokenLine) ->
     { token, { float, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_6/2}).
-file("src/config/config_scanner.xrl", 23).
yyaction_6(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_7/0}).
-file("src/config/config_scanner.xrl", 24).
yyaction_7() ->
     skip_token .

-compile({inline,yyaction_8/2}).
-file("src/config/config_scanner.xrl", 25).
yyaction_8(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_9/2}).
-file("src/config/config_scanner.xrl", 26).
yyaction_9(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_10/2}).
-file("src/config/config_scanner.xrl", 27).
yyaction_10(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_11/2}).
-file("src/config/config_scanner.xrl", 28).
yyaction_11(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_12/3}).
-file("src/config/config_scanner.xrl", 29).
yyaction_12(TokenChars, TokenLen, TokenLine) ->
     { token, { bitstring, TokenLine, strip2 (TokenChars, TokenLen) } } .

-compile({inline,yyaction_13/3}).
-file("src/config/config_scanner.xrl", 30).
yyaction_13(TokenChars, TokenLen, TokenLine) ->
     { token, { hexstring, TokenLine, strip2 (TokenChars, TokenLen) } } .

-compile({inline,yyaction_14/3}).
-file("src/config/config_scanner.xrl", 31).
yyaction_14(TokenChars, TokenLen, TokenLine) ->
     { token, { octetstring, TokenLine, strip2 (TokenChars, TokenLen) } } .

-file("/usr/lib/erlang/lib/parsetools-2.0.12/include/leexinc.hrl", 282).
